#!/bin/bash

main() {
    local -r INPUT="../data/input"

    local longNum="$(cat "$INPUT")"

    local sum=0

    if test ${longNum:0:1} = ${longNum:$((${#longNum} - 1))}; then
        ((sum += ${longNum:0:1}))
    fi

    for ((i=0; i<${#longNum}; ++i)); do
        if test $i -lt $((${#longNum} - 1)); then
            if test ${longNum:$i:1} = ${longNum:$((i + 1)):1}; then
                ((sum += ${longNum:$i:1}))
            fi
        fi
    done

    echo "Result is $sum"
}


main "$@"

