#!/bin/bash

main() {
    local -r INPUT="../data/input"

    local longNum="$(cat "$INPUT")"

    local sum=0

    # For each number in string
    for ((i=0; i<${#longNum}; ++i)); do
        # Calculate other position by adding 1 to it and wrapping
        local otherPos=$((i + 1))
        ((otherPos %= ${#longNum}))

        # If number match then add number to sum
        if test ${longNum:$i:1} = ${longNum:$otherPos:1}; then
            ((sum += ${longNum:$i:1}))
        fi
    done

    echo "Result is $sum"
}


main "$@"

