#!/bin/bash

main() {
    local -r INPUT="../data/input"
    local -A ranges
    local -A currentRanges
    local -i maxDepth=0

    # Read each line
    while read line; do
        # Grab depth and range values from line
        local -i depth=$(echo $line | cut -d':' -f1)
        local -i range=$(echo $line | cut -d' ' -f2)

        # Add value to rules
        ranges[$depth]=$range

        # Set current value
        currentRanges[$depth]=0

        # Find max depth
        if test $depth -gt $maxDepth; then
            maxDepth=$depth
        fi
    done < "$INPUT"

    local -i severity=0

    # Do each move. Player goes first
    for (( depth=0; depth<=maxDepth; ++depth )); do
        # Player move
        echo "Player moves to depth $depth"
        # If there is a scanner at this depth
        if test -n "${currentRanges[$depth]}"; then
            # If we have hit the scanner
            if test ${currentRanges[$depth]} -eq 0; then
                # Add on severity
                (( severity += (depth * ranges[$depth]) ))
                echo -e "\tDetection at depth $depth. Severity increases by ($depth * ${ranges[$depth]})=$(( depth * ranges[$depth] )) to $severity"
            fi
        fi

        # Firewall move
        for scannerDepth in ${!currentRanges[@]}; do
            pos=$(( (depth % (2 * (ranges[$scannerDepth] - 1))) + 1 ))

            if test $pos -ge ${ranges[$scannerDepth]}; then
                (( pos -= (2 * (pos - (ranges[$scannerDepth] - 1))) ))
            fi

            currentRanges[$scannerDepth]=$pos
        done
    done

    echo "Total severity is $severity"
}


main "$@"
