#!/bin/bash

main() {
    local -r INPUT="../data/input"

    declare -a program=( $(cat "$INPUT" | tr '\n' ' ') )

    local -i index=0    
    local -i stepCount=0

    # While we are not out of bounds
    while test $index -ge 0 -a \
               $index -lt ${#program[@]}; do
        # Store old index to use later
        local -i oldIndex=$index

        # Do jump
        (( index += program[$index] ))

        # Increment or decrement number
        if test ${program[$oldIndex]} -ge 3; then
            (( --program[$oldIndex] ))
        else
            (( ++program[$oldIndex] ))
        fi

        # Increment step count
        (( ++stepCount ))
    done

    echo "Took $stepCount steps to exit program"
}


main "$@"

