#!/bin/bash

main() {
    local -r INPUT="../data/input"

    local -A connections;

    # Read each line
    echo "Parsing list..."
    while read line; do
        # Get source number
        local -i source=$(echo $line | cut -d' ' -f1)
        local destinations="$(echo $line | cut -d'>' -f2 | tr -d ',')"

        # Remove starting space
        destinations=${destinations:1}

        # Add connection to list
        connections[$source]="$destinations"
    done < "$INPUT"

    local -i groupCount=0

    while test ${#connections[@]} -ne 0; do
        # Pretty ugly way of getting a valid key from the associative array
        local -a zeroGroup=( $(echo ${!connections[@]} | cut -d' ' -f1) )
        local -i index=0

        # Build of list of programs connected to program this program

        # While we haven't reached the end of the group
        while test $index -ne ${#zeroGroup[@]}; do
            # Look up program in list and loop through connections
            for programNumber in ${connections[${zeroGroup[$index]}]}; do
                # Check if this program number is not in the list
                local found=0
                for i in ${zeroGroup[@]}; do
                    if test $i -eq $programNumber; then
                        found=1

                        break
                    fi
                done

                # If it isn't then add it (zeroGroup increases in size)
                if test $found -eq 0; then
                    zeroGroup[${#zeroGroup[@]}]=$programNumber
                    echo "Adding $programNumber to list"
                fi
            done

            (( ++index ))
        done

        echo "Number of programs in ${zeroGroup[0]} group is ${#zeroGroup[@]}"

        # Remove used up progran numbers
        for programToRemove in ${zeroGroup[@]}; do
            unset connections[$programToRemove];
        done

        (( ++groupCount ))
    done

    echo "Number of distinct groups is $groupCount"
}


main "$@"

