#!/bin/bash

main() {
    local -r INPUT="../data/input"

    while read line; do
        #echo "Line before simplification : $line"

        # Get rid of '!' and chars following '!'
        for ((index=0; index<${#line}; ++index)); do
            if test "${line:$index:1}" = '!'; then
                line="${line:0:$index} ${line:$(( index + 2 ))}"
            fi
        done        
        line="$(echo $line | tr -d " ")"
        #echo -e "\tLine after ! removal : $line"

        # Get rid of sequences between < and >
        local -i garbageRemoved=0
        for ((index=0; index<${#line}; ++index)); do
            if test "${line:$index:1}" = '<'; then
                local -i jndex=$index
                while test "${line:$(( ++jndex )):1}" != '>'; do
                    :
                done
                line="${line:0:$index} ${line:$(( jndex + 1))}"

                # Update count of garbage chars removed
                (( garbageRemoved += ((jndex - 1) - index) ))
            fi
        done
        line="$(echo $line | tr -d " ")"
        #echo -e "\tLine after <> removal : $line"

        #echo "Line after simplification : $line"

        # Parse groups and count
        local -i depth=0
        local -i score=0

        for ((index=0; index<${#line}; ++index)); do
            if test "${line:$index:1}" = '{'; then
                (( score += ++depth ))
            elif test "${line:$index:1}" = '}'; then
                (( --depth ))
            fi
        done

        echo "Score = $score, garbageRemoved = $garbageRemoved"
    done < "$INPUT"
}

main "$@"

