#!/bin/bash

main() {
    local -r INPUT="../data/input"

    local -i sum=0

    while read line; do
        # Read numbers into array
        local -a nums=( $(echo $line) )

        # Fid min and max
        local -i min=99999
        local -i max=0

        for num in "${nums[@]}"; do
            if test $num -gt $max; then
                max=$num
            fi

            if test $num -lt $min; then
                min=$num
            fi
        done

        # Add separation to checksum
        (( sum += (max - min) ))
        echo "Line checksum = $max - $min = $(( max - min )). Running checksum = $sum"
    done < "$INPUT"

    echo "Checksum = $sum"
}


main "$@"

