#!/bin/bash

main() {
    local -r INPUT="../data/input"

    local -i sum=0

    while read line; do
        # Read numbers into array
        local -a nums=( $(echo $line) )

        # Loopo through each number
        for num1 in "${nums[@]}"; do
            # Loop through each other number
            for num2 in "${nums[@]}"; do
                # If they are not the same number and one is divisible by the other
                if test $num1 -ne $num2 -a \
                        $(( num1 % num2 )) -eq 0; then
                    (( sum += (num1 / num2) ))
                    echo "Line checksum = $num1 / $num2 = $(( num1 / num2 )). Running checksum = $sum"

                    break 2
                fi
            done
        done
    done < "$INPUT"

    echo "Checksum = $sum"
}


main "$@"

